version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: banco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
